botmain.js

feature/timetableSwitcher => develop

---

botmain.js
commands/general.js
functions/genshin.js

前半後半切り替えシステム実装

---

botmain.js
commands/general.js
functions/ryoshoku.js

・寮食切り替え通知のON/OFFコマンドを追加(ryoshokuswitcher)
・寮食切り替え通知を外部関数化
・aboutコマンドのnodejsのバージョンを自動で取得するように変更

寮食切り替え通知ON/OFF実装

---

commands/general.js

/secretmsg機能追加

---

botmain.js

ダッシュボード更新時ににconfigを新たに読み込むように変更

dashboardの自動更新機能が、最新版のconfigを使用しない問題を修正

---

commands/general.js

- 改行のみでシークレットメッセージを送信した場合にクラッシュするバグを修正

v4.0.0 Release Candidate 3

---

README.md
botmain.js
commands/createchan.js
commands/dashboard.js
commands/general.js
commands/genshinTimer.js
commands/timeTable.js
functions/dashboard.js
package.json

* pingコマンド実装
* ダッシュボード機能実装
* /secret-msg実装
* /create-chanのバグ修正
* スラッシュコマンド名を平易にした

v4.0.0リリース

---

botmain.js

スラッシュコマンド実行失敗時にエラーを吐くようにしよう

---

commands/dashboard.js
commands/general.js
package.json

- DMでのスラッシュコマンド実行時、一部コマンドで警告を出すように変更
- シークレットメッセージで2000文字以上、および8MB以上のファイルを添付したときに爆発する問題を修正

V4.0.1 Release

---

README.md
botmain.js
commands/dashboard.js
commands/general.js
package.json
timetable/timetableUtils.js

- BOTの名前を「木更津高専統合管理BOT」に変更
- 一時的な措置として、config.server以外のサーバーからのスラッシュコマンドを拒否する仕様に変更。

「スラッシュコマンドを実行してもいいですか？」「そのほうがいいんだろうな。だが断る。」

---

botmain.js
functions/dashboard.js

1分間に自動更新ダッシュボードの回数だけ天気APIにリクエストする問題を修正

---

botmain.js
functions/logsystem.js

ログシステムちょっと修正

---

botmain.js
commands/general.js
commands/guildData.js
functions/weather.js

𝑈𝐿𝑇𝐼𝑀𝐴𝑇𝐸 𝐼𝑀𝑃𝑅𝑂𝑉𝐸𝑀𝐸𝑁𝑇 𝑇𝐼𝑀𝐸です。
- 待望の #95 を実装
- #140 を実装(checkGuild関数使用)
- #145 を適用
- #146 を修正
- #150 を改善(波データ削除、概況を𝑆𝑈𝑃𝐸𝑅 𝑆𝐸𝐼𝐾𝐸𝐼 𝑇𝐼𝑀𝐸した)

𝑈𝐿𝑇𝐼𝑀𝐴𝑇𝐸 𝐼𝑀𝑃𝑅𝑂𝑉𝐸𝑀𝐸𝑁𝑇 𝑇𝐼𝑀𝐸

---

commands/dashboard.js
functions/dashboard.js

nextTestの息の根を止めるプルリク

---

commands/general.js
commands/guildData.js
commands/timeTable.js
functions/dashboard.js
functions/ttGeneration.js
functions/weather.js

- #118 を修正
- #129 を修正
- #121 を適用

fixed weather-switcher & timetable

---

functions/statusAndMode.js

起動時にstatusData is not defined と言ってエラーになる問題を修正

fixed "statusData is not defined"

---

commands/general.js

#133 メンテナンスモード前後にCreateChannelの整合性検証を挟むようにした

---

commands/timeTable.js
functions/ttGeneration.js

- #158 適用済み
- #163 を修正
- 時間割変更のキャッシュが一つしか存在できず、その後おかしくなりそうな問題を修正
- 授業変更時のコメント必須を削除

僕は時間割をより良くしています。AC JAPANも支援してくれそうです(適当)

---

commands/dashboard.js
commands/general.js
commands/timeTable.js
functions/dashboard.js

- #126 を適用
- DMで実行するとエラーでそうなコマンド&AdminコマンドをDMでブロックするように変更
- #172 を修正

スラッシュコマンド改善など

---

botmain.js
functions/logsystem.js
functions/weather.js

- #181 修正done
- #182 修正done
- BOT起動時メンテンナンスモードになるように((最初にconfigからtrueにしてれば、起動時に解除されない))

BUGFIX TIME

---

commands/general.js

V5.0.0 Release Candidata 3
DMで/secret-msgを実行するとエラーを吐く問題を修正

V5.0.0 Release Candidata 3

---

botmain.js

v5.0.0 RC4適用

---

botmain.js
functions/dashboard.js
functions/weather.js

v5.0.0 Release Candidate 5

---

botmain.js
commands/dashboard.js
commands/general.js
commands/guildData.js
commands/timeTable.js
functions/birthday.js
functions/dashboard.js
functions/guildDataSet.js
functions/ttGeneration.js

- 天気予報通知を別データに分離(guildDataSystem)
- setDMPermissionの導入
- メンテナンスモード中セレクトメニュー等でクラッシュする問題を修正
- auto-dashboardが存在するチャンネルが削除されたときに爆発していた問題を修正
- n秒後に削除します　が出た後該当チャンネルを削除すると爆発していた問題を修正
- 授業変更Uiのメッセージやチャンネルの削除時に爆発していた問題を修正
- dashboard.jsのgeneration関数の安全性をあげました
- 誕生日通知の安全性をあげました

v5.0.0 Release Candidata 7

---

commands/timeTable.js

- データ未登録の学科・学年を指定したとき、comment-timetableとadd-exceptionが落ちる問題を修正

v5.0.0 RC8適用

---

commands/timeTable.js

- データ未登録の学科・学年を指定したとき、comment-timetableとadd-exceptionが落ちる問題を修正

v5.0.0 Release Candidata 8

---

commands/guildData.js

/guildDataがうまく動かない問題を修正

---

botmain.js
commands/timeTable.js
package.json

- 授業へのコメント登録が失敗するときがある問題を修正
- 天気予報の時間割が間違っている問題を修正

v5.0.1 Release

---

botmain.js

BOT起動時にguildの整合性を確認するよう変更

---

commands/general.js
package.json

hotfix/SecretMessage #224
